import type { Appointment } from "./types";

export const DEMO_APPOINTMENTS: Appointment[] = [
  // ── March 5 ──
  { id: "apt-01", patientName: "James Wilson",     patientEmail: "j.wilson@mail.com",    patientPhone: "07700 100001", serviceName: "Flu Vaccination",           serviceId: "v-1",  providerId: "usr-1", providerName: "Mrs. Sarah Johnson",  providerColor: "blue",    date: "2026-03-05", startTime: "09:00", endTime: "09:15", status: "completed", notes: "" },
  { id: "apt-02", patientName: "Olivia Brown",     patientEmail: "o.brown@mail.com",     patientPhone: "07700 100002", serviceName: "Pharmacist Consultation",   serviceId: "c-1",  providerId: "usr-2", providerName: "Mr. Michael Chen",   providerColor: "violet",  date: "2026-03-05", startTime: "09:30", endTime: "09:50", status: "completed", notes: "Follow-up needed" },
  { id: "apt-03", patientName: "Liam Davies",      patientEmail: "l.davies@mail.com",    patientPhone: "07700 100003", serviceName: "Blood Pressure Check",      serviceId: "s-1",  providerId: "usr-3", providerName: "Miss Emily Williams", providerColor: "emerald", date: "2026-03-05", startTime: "10:00", endTime: "10:10", status: "no-show",   notes: "" },
  // ── March 6 ──
  { id: "apt-04", patientName: "Emma Thompson",    patientEmail: "e.thompson@mail.com",  patientPhone: "07700 100004", serviceName: "COVID-19 Booster",          serviceId: "v-2",  providerId: "usr-1", providerName: "Mrs. Sarah Johnson",  providerColor: "blue",    date: "2026-03-06", startTime: "09:00", endTime: "09:15", status: "confirmed", notes: "" },
  { id: "apt-05", patientName: "Noah Evans",       patientEmail: "n.evans@mail.com",     patientPhone: "07700 100005", serviceName: "Chronic Disease Management",serviceId: "c-2",  providerId: "usr-2", providerName: "Mr. Michael Chen",   providerColor: "violet",  date: "2026-03-06", startTime: "10:00", endTime: "10:30", status: "confirmed", notes: "Diabetes review" },
  { id: "apt-06", patientName: "Sophia Roberts",   patientEmail: "s.roberts@mail.com",   patientPhone: "07700 100006", serviceName: "Comprehensive Med Review",  serviceId: "m-1",  providerId: "usr-3", providerName: "Miss Emily Williams", providerColor: "emerald", date: "2026-03-06", startTime: "11:00", endTime: "11:30", status: "pending",   notes: "" },
  // ── March 9 ──
  { id: "apt-07", patientName: "George Hall",      patientEmail: "g.hall@mail.com",      patientPhone: "07700 100007", serviceName: "Pre-Travel Consultation",   serviceId: "t-1",  providerId: "usr-1", providerName: "Mrs. Sarah Johnson",  providerColor: "blue",    date: "2026-03-09", startTime: "09:00", endTime: "09:30", status: "confirmed", notes: "Trip to Thailand" },
  { id: "apt-08", patientName: "Amelia Walker",    patientEmail: "a.walker@mail.com",    patientPhone: "07700 100008", serviceName: "Smoking Cessation Program", serviceId: "c-3",  providerId: "usr-2", providerName: "Mr. Michael Chen",   providerColor: "violet",  date: "2026-03-09", startTime: "11:00", endTime: "11:30", status: "pending",   notes: "Session 2 of 6" },
  // ── March 10 ──
  { id: "apt-09", patientName: "Harry Taylor",     patientEmail: "h.taylor@mail.com",    patientPhone: "07700 100009", serviceName: "Cholesterol Panel",         serviceId: "s-3",  providerId: "usr-3", providerName: "Miss Emily Williams", providerColor: "emerald", date: "2026-03-10", startTime: "09:00", endTime: "09:15", status: "confirmed", notes: "" },
  { id: "apt-10", patientName: "Isla Thomas",      patientEmail: "i.thomas@mail.com",    patientPhone: "07700 100010", serviceName: "Flu Vaccination",           serviceId: "v-1",  providerId: "usr-1", providerName: "Mrs. Sarah Johnson",  providerColor: "blue",    date: "2026-03-10", startTime: "10:00", endTime: "10:15", status: "cancelled", notes: "Patient requested cancellation" },
  // ── March 12 ──
  { id: "apt-11", patientName: "Jack Anderson",    patientEmail: "j.anderson@mail.com",  patientPhone: "07700 100011", serviceName: "Blister Packaging",         serviceId: "d-3",  providerId: "usr-2", providerName: "Mr. Michael Chen",   providerColor: "violet",  date: "2026-03-12", startTime: "09:00", endTime: "09:10", status: "confirmed", notes: "" },
  { id: "apt-12", patientName: "Mia White",        patientEmail: "m.white@mail.com",     patientPhone: "07700 100012", serviceName: "Shingles Vaccine",          serviceId: "v-3",  providerId: "usr-1", providerName: "Mrs. Sarah Johnson",  providerColor: "blue",    date: "2026-03-12", startTime: "14:00", endTime: "14:20", status: "confirmed", notes: "Dose 1" },
  // ── March 16 ──
  { id: "apt-13", patientName: "Oscar Harris",     patientEmail: "o.harris@mail.com",    patientPhone: "07700 100013", serviceName: "Rapid Strep / Flu Test",    serviceId: "s-4",  providerId: "usr-3", providerName: "Miss Emily Williams", providerColor: "emerald", date: "2026-03-16", startTime: "09:30", endTime: "09:45", status: "pending",   notes: "" },
  { id: "apt-14", patientName: "Charlotte Clark",  patientEmail: "c.clark@mail.com",     patientPhone: "07700 100014", serviceName: "Therapy Optimization",      serviceId: "m-2",  providerId: "usr-2", providerName: "Mr. Michael Chen",   providerColor: "violet",  date: "2026-03-16", startTime: "11:00", endTime: "11:20", status: "confirmed", notes: "" },
  // ── March 19 ──
  { id: "apt-15", patientName: "Freddie Lewis",    patientEmail: "f.lewis@mail.com",     patientPhone: "07700 100015", serviceName: "Travel Vaccinations",       serviceId: "t-2",  providerId: "usr-1", providerName: "Mrs. Sarah Johnson",  providerColor: "blue",    date: "2026-03-19", startTime: "09:00", endTime: "09:30", status: "confirmed", notes: "Hepatitis A + Typhoid" },
  // ── March 23 ──
  { id: "apt-16", patientName: "Poppy Robinson",   patientEmail: "p.robinson@mail.com",  patientPhone: "07700 100016", serviceName: "Adherence Coaching",        serviceId: "m-3",  providerId: "usr-3", providerName: "Miss Emily Williams", providerColor: "emerald", date: "2026-03-23", startTime: "10:00", endTime: "10:15", status: "pending",   notes: "" },
  // ── March 26 ──
  { id: "apt-17", patientName: "Oliver Mitchell",  patientEmail: "o.mitchell@mail.com",  patientPhone: "07700 100017", serviceName: "Blood Glucose Test",        serviceId: "s-2",  providerId: "usr-2", providerName: "Mr. Michael Chen",   providerColor: "violet",  date: "2026-03-26", startTime: "09:00", endTime: "09:10", status: "confirmed", notes: "" },
  { id: "apt-18", patientName: "Emily Scott",      patientEmail: "e.scott@mail.com",     patientPhone: "07700 100018", serviceName: "Childhood Immunizations",   serviceId: "v-4",  providerId: "usr-1", providerName: "Mrs. Sarah Johnson",  providerColor: "blue",    date: "2026-03-26", startTime: "14:00", endTime: "14:30", status: "confirmed", notes: "MMR + DTaP" },
];
