import type { ServiceMetadata } from "./types";

// ── Demo services ────────────────────────────────────────────────
export const DEMO_SERVICES: ServiceMetadata[] = [
  {
    id: "svc-001",
    pharmacyId: "ph-001",
    name: "Flu Vaccination",
    internalCode: "VAC-FLU-01",
    categoryId: "vaccination",
    status: "active",
    shortDescription: "Annual influenza immunization for all ages 6 months and up.",
    fullDescriptionHtml: "<p>Protect yourself and your family this flu season with our annual influenza vaccination. Administered by certified pharmacists in a comfortable clinical setting.</p>",
    durationMinutes: 15,
    bufferMinutes: 5,
    bookingWindowDays: 90,
    minNoticeHours: 2,
    maxCapacityPerSlot: 1,
    allowWaitlist: false,
    cancellationPolicy: "Free cancellation up to 2 hours before appointment.",
    requiresPrescription: false,
    ageMin: null,
    ageMax: null,
    genderRestriction: "any",
    preAppointmentInstructions: "Wear a short-sleeve shirt. Inform staff of any allergies.",
    contraindicationsWarning: "Not suitable for those with severe egg allergies.",
    consentFormRequired: true,
    heroImageUrl: "",
    thumbnailUrl: "",
    iconKey: "syringe",
    isFeatured: true,
    videoUrl: "",
    pricePublic: 0,
    currency: "GBP",
    requiredRole: "pharmacist",
    roomLocation: "Injection Room",
    inventoryLink: "INV-FLU-VIAL",
    internalNotes: "Check stock levels weekly during flu season.",
    priceInternal: 8.5,
    slug: "flu-vaccination",
    metaTitle: "Flu Vaccination | VivIPractice Pharmacy",
    metaDescription: "Get your annual flu shot at VivIPractice. Walk-ins welcome. Administered by certified pharmacists.",
    keywords: ["flu", "vaccination", "immunization", "influenza"],
    createdAt: "2025-11-01T09:00:00Z",
    updatedAt: "2026-02-15T14:30:00Z",
    createdBy: "admin@vivipractice.com",
  },
  {
    id: "svc-002",
    pharmacyId: "ph-001",
    name: "Pharmacist Consultation",
    internalCode: "CON-PHARM-01",
    categoryId: "consultation",
    status: "active",
    shortDescription: "One-on-one consultation with a licensed pharmacist.",
    fullDescriptionHtml: "<p>Discuss your health concerns, medication questions, and treatment options with our experienced pharmacists in a private consultation room.</p>",
    durationMinutes: 20,
    bufferMinutes: 5,
    bookingWindowDays: 60,
    minNoticeHours: 4,
    maxCapacityPerSlot: 1,
    allowWaitlist: true,
    cancellationPolicy: "24-hour cancellation notice required.",
    requiresPrescription: false,
    ageMin: null,
    ageMax: null,
    genderRestriction: "any",
    preAppointmentInstructions: "Bring a list of your current medications.",
    contraindicationsWarning: "",
    consentFormRequired: false,
    heroImageUrl: "",
    thumbnailUrl: "",
    iconKey: "chat",
    isFeatured: true,
    videoUrl: "",
    pricePublic: null,
    currency: "GBP",
    requiredRole: "pharmacist",
    roomLocation: "Consultation Room 1",
    inventoryLink: "",
    internalNotes: "",
    priceInternal: null,
    slug: "pharmacist-consultation",
    metaTitle: "",
    metaDescription: "",
    keywords: ["consultation", "pharmacist", "advice"],
    createdAt: "2025-11-01T09:00:00Z",
    updatedAt: "2026-01-20T10:00:00Z",
    createdBy: "admin@vivipractice.com",
  },
  {
    id: "svc-003",
    pharmacyId: "ph-001",
    name: "Comprehensive Medication Review",
    internalCode: "MED-CMR-01",
    categoryId: "medication",
    status: "active",
    shortDescription: "Full evaluation of all medications for safety and efficacy.",
    fullDescriptionHtml: "<p>Our pharmacists will review all your prescriptions, over-the-counter drugs, and supplements to identify interactions, optimize therapy, and simplify your regimen.</p>",
    durationMinutes: 30,
    bufferMinutes: 10,
    bookingWindowDays: 90,
    minNoticeHours: 24,
    maxCapacityPerSlot: 1,
    allowWaitlist: false,
    cancellationPolicy: "48-hour cancellation notice required. £25 late cancellation fee.",
    requiresPrescription: false,
    ageMin: 18,
    ageMax: null,
    genderRestriction: "any",
    preAppointmentInstructions: "Bring ALL medications including supplements and OTC drugs.",
    contraindicationsWarning: "",
    consentFormRequired: true,
    heroImageUrl: "",
    thumbnailUrl: "",
    iconKey: "clipboard",
    isFeatured: false,
    videoUrl: "",
    pricePublic: 35,
    currency: "GBP",
    requiredRole: "pharmacist",
    roomLocation: "Consultation Room 2",
    inventoryLink: "",
    internalNotes: "Allocate extra 10 mins for patients with 10+ medications.",
    priceInternal: 15,
    slug: "comprehensive-medication-review",
    metaTitle: "Medication Review | VivIPractice Pharmacy",
    metaDescription: "Get a comprehensive review of all your medications by a certified pharmacist. Optimize your therapy today.",
    keywords: ["medication", "review", "therapy", "optimization"],
    createdAt: "2025-11-15T09:00:00Z",
    updatedAt: "2026-02-01T11:00:00Z",
    createdBy: "admin@vivipractice.com",
  },
  {
    id: "svc-004",
    pharmacyId: "ph-001",
    name: "Pre-Travel Consultation",
    internalCode: "TRV-CON-01",
    categoryId: "travel",
    status: "active",
    shortDescription: "Risk assessment and recommended vaccinations for your destination.",
    fullDescriptionHtml: "<p>Planning a trip? Our travel health experts will assess your destination risks, recommend required and optional vaccinations, and provide preventive medications.</p>",
    durationMinutes: 30,
    bufferMinutes: 5,
    bookingWindowDays: 120,
    minNoticeHours: 48,
    maxCapacityPerSlot: 1,
    allowWaitlist: false,
    cancellationPolicy: "72-hour cancellation notice required.",
    requiresPrescription: false,
    ageMin: null,
    ageMax: null,
    genderRestriction: "any",
    preAppointmentInstructions: "Bring your travel itinerary and vaccination records.",
    contraindicationsWarning: "",
    consentFormRequired: true,
    heroImageUrl: "",
    thumbnailUrl: "",
    iconKey: "globe",
    isFeatured: true,
    videoUrl: "",
    pricePublic: 45,
    currency: "GBP",
    requiredRole: "pharmacist",
    roomLocation: "Consultation Room 1",
    inventoryLink: "",
    internalNotes: "Refer to CDC Travelers' Health for latest advisories.",
    priceInternal: 20,
    slug: "pre-travel-consultation",
    metaTitle: "Travel Health Consultation | VivIPractice",
    metaDescription: "Get travel health advice and vaccinations before your trip. Expert consultation by certified pharmacists.",
    keywords: ["travel", "health", "vaccination", "consultation"],
    createdAt: "2025-12-01T09:00:00Z",
    updatedAt: "2026-02-10T16:00:00Z",
    createdBy: "admin@vivipractice.com",
  },
  {
    id: "svc-005",
    pharmacyId: "ph-001",
    name: "Blood Pressure Monitoring",
    internalCode: "SCR-BP-01",
    categoryId: "screening",
    status: "active",
    shortDescription: "Quick and accurate digital blood pressure screening.",
    fullDescriptionHtml: "<p>Get an accurate blood pressure reading using clinical-grade equipment. Results are recorded and can be shared with your healthcare provider.</p>",
    durationMinutes: 10,
    bufferMinutes: 0,
    bookingWindowDays: 30,
    minNoticeHours: 1,
    maxCapacityPerSlot: 2,
    allowWaitlist: false,
    cancellationPolicy: "Free cancellation anytime.",
    requiresPrescription: false,
    ageMin: null,
    ageMax: null,
    genderRestriction: "any",
    preAppointmentInstructions: "Avoid caffeine and exercise 30 minutes before your reading.",
    contraindicationsWarning: "",
    consentFormRequired: false,
    heroImageUrl: "",
    thumbnailUrl: "",
    iconKey: "heart",
    isFeatured: false,
    videoUrl: "",
    pricePublic: 0,
    currency: "GBP",
    requiredRole: "technician",
    roomLocation: "Screening Station",
    inventoryLink: "",
    internalNotes: "Use Omron HEM-907XL device. Calibrate monthly.",
    priceInternal: 2,
    slug: "blood-pressure-monitoring",
    metaTitle: "",
    metaDescription: "",
    keywords: ["blood pressure", "screening", "monitoring", "heart health"],
    createdAt: "2025-12-15T09:00:00Z",
    updatedAt: "2026-01-25T09:00:00Z",
    createdBy: "admin@vivipractice.com",
  },
  {
    id: "svc-006",
    pharmacyId: "ph-001",
    name: "Prescription Pickup",
    internalCode: "DIS-PICK-01",
    categoryId: "dispensing",
    status: "active",
    shortDescription: "Scheduled pickup window — skip the wait.",
    fullDescriptionHtml: "<p>Reserve a pickup window for your prescription and walk straight to the counter. No more waiting in line.</p>",
    durationMinutes: 5,
    bufferMinutes: 0,
    bookingWindowDays: 14,
    minNoticeHours: 1,
    maxCapacityPerSlot: 4,
    allowWaitlist: false,
    cancellationPolicy: "Free cancellation anytime.",
    requiresPrescription: true,
    ageMin: null,
    ageMax: null,
    genderRestriction: "any",
    preAppointmentInstructions: "Bring your prescription and insurance card.",
    contraindicationsWarning: "",
    consentFormRequired: false,
    heroImageUrl: "",
    thumbnailUrl: "",
    iconKey: "bag",
    isFeatured: false,
    videoUrl: "",
    pricePublic: null,
    currency: "GBP",
    requiredRole: "technician",
    roomLocation: "Dispensary Counter",
    inventoryLink: "",
    internalNotes: "Verify prescription validity before handing over.",
    priceInternal: null,
    slug: "prescription-pickup",
    metaTitle: "",
    metaDescription: "",
    keywords: ["prescription", "pickup", "dispensing"],
    createdAt: "2026-01-05T09:00:00Z",
    updatedAt: "2026-02-20T12:00:00Z",
    createdBy: "admin@vivipractice.com",
  },
  {
    id: "svc-007",
    pharmacyId: "ph-001",
    name: "COVID-19 Booster",
    internalCode: "VAC-COVID-B1",
    categoryId: "vaccination",
    status: "draft",
    shortDescription: "Updated mRNA booster for enhanced protection.",
    fullDescriptionHtml: "<p>Stay protected with the latest COVID-19 booster. Administered by certified pharmacists following current CDC guidelines.</p>",
    durationMinutes: 15,
    bufferMinutes: 15,
    bookingWindowDays: 60,
    minNoticeHours: 2,
    maxCapacityPerSlot: 1,
    allowWaitlist: true,
    cancellationPolicy: "Free cancellation up to 2 hours before appointment.",
    requiresPrescription: false,
    ageMin: 12,
    ageMax: null,
    genderRestriction: "any",
    preAppointmentInstructions: "Wait 15 minutes after injection for observation. Bring previous vaccination records.",
    contraindicationsWarning: "Not recommended for those who had severe allergic reaction to a prior COVID vaccine dose.",
    consentFormRequired: true,
    heroImageUrl: "",
    thumbnailUrl: "",
    iconKey: "syringe",
    isFeatured: false,
    videoUrl: "",
    pricePublic: 0,
    currency: "GBP",
    requiredRole: "pharmacist",
    roomLocation: "Injection Room",
    inventoryLink: "INV-COVID-MRNA",
    internalNotes: "Requires 15-min observation period. Stock stored at -20°C.",
    priceInternal: 12,
    slug: "covid-19-booster",
    metaTitle: "",
    metaDescription: "",
    keywords: ["covid", "booster", "vaccination", "mrna"],
    createdAt: "2026-01-15T09:00:00Z",
    updatedAt: "2026-02-28T14:00:00Z",
    createdBy: "admin@vivipractice.com",
  },
  {
    id: "svc-008",
    pharmacyId: "ph-001",
    name: "Smoking Cessation Program",
    internalCode: "CON-SMOKE-01",
    categoryId: "consultation",
    status: "archived",
    shortDescription: "Personalized quit plan with NRT guidance and follow-up sessions.",
    fullDescriptionHtml: "<p>Our evidence-based smoking cessation program provides personalized counseling, nicotine replacement therapy options, and scheduled follow-ups to support your journey to becoming smoke-free.</p>",
    durationMinutes: 30,
    bufferMinutes: 5,
    bookingWindowDays: 60,
    minNoticeHours: 24,
    maxCapacityPerSlot: 1,
    allowWaitlist: false,
    cancellationPolicy: "24-hour cancellation notice required.",
    requiresPrescription: false,
    ageMin: 18,
    ageMax: null,
    genderRestriction: "any",
    preAppointmentInstructions: "Complete the Fagerström Test for Nicotine Dependence online before your visit.",
    contraindicationsWarning: "",
    consentFormRequired: true,
    heroImageUrl: "",
    thumbnailUrl: "",
    iconKey: "heart",
    isFeatured: false,
    videoUrl: "",
    pricePublic: 50,
    currency: "GBP",
    requiredRole: "pharmacist",
    roomLocation: "Consultation Room 2",
    inventoryLink: "",
    internalNotes: "Program archived — resuming in Q3 2026.",
    priceInternal: 25,
    slug: "smoking-cessation-program",
    metaTitle: "Smoking Cessation | VivIPractice Pharmacy",
    metaDescription: "Quit smoking with expert guidance from VivIPractice pharmacists. Personalized NRT plans and ongoing support.",
    keywords: ["smoking", "cessation", "quit", "nrt", "counseling"],
    createdAt: "2025-10-01T09:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
    createdBy: "admin@vivipractice.com",
  },
];
